use_default_settings: true

general:
  debug: false
  privacypolicy_url: false
  donation_url: false
  contact_url: false

server:
  secret_key: c379f730d3bdd498af76833a45da09897966dc1a83ae0e0ae5343c00f727ce79
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true
  query_in_title: false
  default_theme: simple
  theme_args:
    simple_style: auto
  search_on_category_select: true
  hotkeys: default
  url_formatting: pretty
  center_alignment: true
  preferences:
    lock:
      - categories
      - language
      - autocomplete
      - favicon
      - safesearch
      - method
      - doi_resolver
      - theme
      - results_on_new_tab
      - infinite_scroll
      - search_on_category_select
      - image_proxy
      - query_in_title
  
redis:
  url: 'redis://valkey:6379/0'

search:
  safe_search: 0
  autocomplete: "google"
  autocomplete_min: 4
  favicon_resolver: "google"
  default_lang: "auto"
  formats:
    - html
    - json
    - rss
    - csv

plugins:

  searx.plugins.calculator.SXNGPlugin:
    active: true

  searx.plugins.hash_plugin.SXNGPlugin:
    active: true

  searx.plugins.self_info.SXNGPlugin:
    active: true

  searx.plugins.unit_converter.SXNGPlugin:
    active: true

  searx.plugins.ahmia_filter.SXNGPlugin:
    active: true

  searx.plugins.hostnames.SXNGPlugin:
    active: true

  searx.plugins.oa_doi_rewrite.SXNGPlugin:
    active: true

  searx.plugins.tor_check.SXNGPlugin:
    active: true

  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true
