[favicons]
cfg_schema = 1
[favicons.cache]
db_url = "/var/cache/searxng/faviconcache.db"
[favicons.proxy]
max_age = 5184000
[favicons.proxy.resolver_map]
"duckduckgo" = "searx.favicons.resolvers.duckduckgo"
"allesedv" = "searx.favicons.resolvers.allesedv"
"google" = "searx.favicons.resolvers.google"
"yandex" = "searx.favicons.resolvers.yandex"