name: 'PFM-Upstream-Sync'

env:
  UPSTREAM_REPO: searxng/searxng
  UPSTREAM_BRANCH: master
  TARGET_BRANCH: main

on:
  schedule:
    - cron: "0 20 * * *" # 每天04点
    - cron: "0 8 * * *" # 每天16点
  workflow_dispatch:
    inputs:
      sync_test_mode:
        description: '同步测试模式'
        type: boolean
        default: false

concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

permissions: write-all

jobs:
  Sync_Latest_From_UpStream:
    name: '同步上游仓库最新提交'
    runs-on: ubuntu-latest
    outputs:
      has_new_commits: ${{ steps.sync.outputs.has_new_commits }}
      has_new_tags: ${{ steps.sync.outputs.has_new_tags }}
      version: ${{ steps.sync.outputs.version }}

    steps:
      - name: '检出分支'
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_BRANCH }}
          persist-credentials: false
          fetch-depth: 1

      - name: '同步变化'
        id: sync
        uses: PFM-PowerForMe/Action-Fork-Sync-With-Upstream-action@main
        with:
          upstream_sync_repo: ${{ env.UPSTREAM_REPO }}
          upstream_sync_branch: ${{ env.UPSTREAM_BRANCH }}
          target_sync_branch: ${{ env.TARGET_BRANCH }}
          target_repo_token: ${{ secrets.SYNC_TOKEN }}

      - name: '同步失败'
        if: failure()
        run: |
          echo "[Error] 由于上游仓库工作流文件的更改，GitHub 已自动暂停了计划的自动更新。您需要手动同步您的复刻。"
          exit 1

  Call-next-workflow:
    needs: Sync_Latest_From_UpStream
    if: needs.Sync_Latest_From_UpStream.outputs.has_new_commits == 'true'
    permissions: write-all
    uses: ./.github/workflows/custom-container-build.yml
    secrets: inherit
